---
- src: https://github.com/robertdebock/ansible-role-bootstrap.git
  version: 2.11.0
  name: robertdebock.bootstrap
- src: https://github.com/jkirk/ansible-role-user.git
  version: ddc9437
  name: jkirk.user
- src: https://github.com/jkirk/ansible-role-base.git
  version: ded16c9
  name: jkirk.base
- src: https://github.com/jkirk/ansible-role-grml-config.git
  version: bf34cce
  name: jkirk.grml-config
- src: https://github.com/jkirk/ansible-role-template.git
  version: 65e9537
  name: jkirk.template
- src: https://github.com/Oefenweb/ansible-hostname.git
  name: Oefenweb.hostname
  version: 04388545

