---
- src: https://github.com/jkirk/ansible-restic-rest
  version: 0588f36
  name: donat-b.restic-rest
- src: https://github.com/jkirk/ansible-role-base.git
  version: eb2c6e2
  name: jkirk.base
- src: https://github.com/jkirk/ansible-role-grml-config.git
  version: 7a94275
  name: jkirk.grml-config
- src: https://github.com/jkirk/ansible-role-letsencrypt.git
  version: 51f6e0d
  name: jkirk.letsencrypt
- src: https://github.com/jkirk/ansible-role-proxmox.git
  version: 244ce630
  name: jkirk.proxmox
- src: https://github.com/jkirk/ansible-role-template.git
  version: 79a2acb
  name: jkirk.template
- src: https://github.com/jkirk/ansible-role-user.git
  version: 96e01ca
  name: jkirk.user
- src: https://github.com/jkirk/ansible-role-website.git
  version: 0810b32
  name: jkirk.website
- src: https://github.com/jnv/ansible-role-unattended-upgrades.git
  version: 392df31
  name: jnv.unattended-upgrades
- src: https://github.com/Oefenweb/ansible-hostname
  version: fd9e966
  name: Oefenweb.hostname
- src: https://github.com/jkirk/ansible-restic.git
  version: c9ce00a
  name: paulfantom.restic
- src: https://github.com/robertdebock/ansible-role-bootstrap.git
  version: 5.0.3
  name: robertdebock.bootstrap
- src: shibumi.systemd-conf
  version: c233062
  name: shibumi.systemd-conf
