---
roles:
- src: https://github.com/donat-b/ansible-restic-rest
  version: e73253b
  name: donat-b.restic-rest
- src: https://github.com/jkirk/ansible-role-base.git
  version: d99c080
  name: jkirk.base
- src: https://github.com/jkirk/ansible-role-checkmkagent.git
  version: 0d86d36
  name: jkirk.checkmkagent
- src: https://github.com/jkirk/ansible-role-grml-config.git
  version: d4a81a3
  name: jkirk.grml-config
- src: https://github.com/jkirk/ansible-role-letsencrypt.git
  version: 51f6e0d
  name: jkirk.letsencrypt
- src: https://github.com/jkirk/ansible-role-proxmox.git
  version: 0a2738a
  name: jkirk.proxmox
- src: https://github.com/jkirk/ansible-role-template.git
  version: 63ec571
  name: jkirk.template
- src: https://github.com/jkirk/ansible-role-user.git
  version: 4abc44c
  name: jkirk.user
- src: https://github.com/jkirk/ansible-role-website.git
  version: 94d69ea
  name: jkirk.website
- src: https://github.com/jnv/ansible-role-unattended-upgrades.git
  version: f9e09a3
  name: jnv.unattended-upgrades
  # This role is deprecated, please migrate to role hifis.toolkit.unattended_upgrades
- src: https://github.com/Oefenweb/ansible-hostname
  version: v2.0.24
  name: Oefenweb.hostname
- src: https://github.com/jkirk/ansible-restic.git
  version: b9dddd7
  name: paulfantom.restic
- src: https://github.com/robertdebock/ansible-role-bootstrap.git
  version: 6.2.4
  name: robertdebock.bootstrap
- src: https://github.com/robertdebock/ansible-role-users
  version: 6.1.5
  name: robertdebock.users
- src: shibumi.systemd-conf
  version: c233062
  name: shibumi.systemd-conf
collections:
- name: hifis.toolkit
  # This collection replaces the deprecated role jnv.unattended-upgrades, please migrate to hifis.toolkit.unattended_upgrades
  version: 4.2.0
