---
- src: https://github.com/donat-b/ansible-restic-rest
  version: e73253b
  name: donat-b.restic-rest
- src: https://github.com/jkirk/ansible-role-base.git
  version: e61776c
  name: jkirk.base
- src: https://github.com/jkirk/ansible-role-checkmkagent.git
  version: 4fe6230
  name: jkirk.checkmkagent
- src: https://github.com/jkirk/ansible-role-grml-config.git
  version: d4a81a3
  name: jkirk.grml-config
- src: https://github.com/jkirk/ansible-role-letsencrypt.git
  version: 51f6e0d
  name: jkirk.letsencrypt
- src: https://github.com/jkirk/ansible-role-proxmox.git
  version: 0a2738a
  name: jkirk.proxmox
- src: https://github.com/jkirk/ansible-role-template.git
  version: da52113
  name: jkirk.template
- src: https://github.com/jkirk/ansible-role-user.git
  version: 70bfd77
  name: jkirk.user
- src: https://github.com/jkirk/ansible-role-website.git
  version: 94d69ea
  name: jkirk.website
- src: https://github.com/jnv/ansible-role-unattended-upgrades.git
  version: f9e09a3
  name: jnv.unattended-upgrades
- src: https://github.com/Oefenweb/ansible-hostname
  version: fd9e966
  name: Oefenweb.hostname
- src: https://github.com/jkirk/ansible-restic.git
  version: 4052be1
  name: paulfantom.restic
- src: https://github.com/robertdebock/ansible-role-bootstrap.git
  version: 5.2.12
  name: robertdebock.bootstrap
- src: shibumi.systemd-conf
  version: c233062
  name: shibumi.systemd-conf
