---
- src: https://github.com/jkirk/ansible-role-base.git
  version: a3ef95a
  name: jkirk.base
- src: https://github.com/jkirk/ansible-role-grml-config.git
  version: ca0c35d
  name: jkirk.grml-config
- src: https://github.com/jkirk/ansible-role-letsencrypt.git
  version: 51f6e0d
  name: jkirk.letsencrypt
- src: https://github.com/jkirk/ansible-role-proxmox.git
  name: jkirk.proxmox
  version: 73c832d
- src: https://github.com/jkirk/ansible-role-template.git
  version: 895ccca
  name: jkirk.template
- src: https://github.com/jkirk/ansible-role-user.git
  version: ddc9437
  name: jkirk.user
- src: https://github.com/donat-b/ansible-restic-rest.git
  version: c7c8239
  name: donat-b.restic-rest
- src: https://github.com/jkirk/ansible-role-unattended-upgrades.git
  version: bbe5b52
  name: jnv.unattended-upgrades
- src: https://github.com/Oefenweb/ansible-hostname.git
  version: 04388545
  name: Oefenweb.hostname
- src: https://github.com/jkirk/ansible-restic.git
  version: f80930a3
  name: paulfantom.restic
- src: https://github.com/robertdebock/ansible-role-bootstrap.git
  version: 4.1.5
  name: robertdebock.bootstrap
- src: shibumi.systemd-conf
  version: c233062
  name: shibumi.systemd-conf
