---
- src: https://github.com/robertdebock/ansible-role-bootstrap.git
  version: 2.11.0
  name: robertdebock.bootstrap
- src: https://github.com/jkirk/ansible-role-user.git
  version: 2374457e21a8324b791069a6044292bc3310ecd1
  name: jkirk.user
- src: https://github.com/jkirk/ansible-role-base.git
  version: ad53cb7
  name: jkirk.base
- src: https://github.com/jkirk/ansible-role-grml-config.git
  version: 2008580ab46e2d6b521276dcc5656e982f061894
  name: jkirk.grml-config
- src: https://github.com/jkirk/ansible-role-template.git
  version: 65e9537
  name: jkirk.template
- src: https://github.com/Oefenweb/ansible-hostname.git
  name: Oefenweb.hostname
  version: 04388545

