---

- name: Setup site wide base configuration
  hosts: site
  become: yes
  roles:
    - role: jkirk.base
    - role: Oefenweb.hostname
    - { role: jkirk.grml-config, username: "root" }
    - { role: jkirk.grml-config, username: "jane_doe" }
    - { role: jkirk.grml-config, username: "john_doe" }
