---

- name: Setup site wide unattended-upgrades configuration
  hosts: site
  become: yes
  roles:
    - role: jnv.unattended-upgrades
      unattended_minimal_steps: true
      unattended_origins_patterns: [
        "origin=Debian,codename=${distro_codename},label=Debian-Security",
        "origin=Debian,codename=${distro_codename},label=Debian",
        "origin=Debian,codename=${distro_codename}-updates,label=Debian",
      ]
